name: find-me

services: 
  slon:
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfiles/DB
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: master
      POSTGRES_DB: mydb
    volumes:
      - db:/app/persistent
  api:
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfiles/API
    depends_on:
      - slon
    ports:
      - 5000:5000

volumes:
  db: